version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=fbstats

  redis:
    image: redis:latest

  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.0
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: ./compose/django/start-dev.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=fbstats
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres
      - redis
      - rabbit

  # Celery worker
  worker:
    build:
      context: .
      dockerfile: ./compose/celery/Dockerfile
    command: /run_celery.sh
    volumes:
      - .:/app
    links:
      - postgres
      - rabbit
      - redis
    depends_on:
      - rabbit
