version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  redis:
    image: redis:latest

  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.0
    # environment:
    #   - RABBITMQ_DEFAULT_USER=admin
    #   - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin


  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
      - rabbit
      - worker
    command: /gunicorn.sh
    env_file: .env
    links:
      - worker
      - rabbit

  # Celery worker
  worker:
    build:
      context: .
      dockerfile: ./compose/celery/Dockerfile
    command: /run_celery.sh
    volumes:
      - .:/app
    links:
      - postgres
      - rabbit
      - redis
    depends_on:
      - rabbit

  nginx:
    build: ./compose/nginx
    depends_on:
      - django

    ports:
      - "0.0.0.0:80:80"